module Plugin () where

import Network.WtsDvc.Client.TH
import System.IO (hFlush, stdout)

initialize :: IO ()
initialize = do
    putStrLn "Haskell is running, and the entry point"
    putStrLn "together with its foreign export"
    putStrLn "is generated by Template Haskell!"
    putStrLn "Also the library size didn't grow."
    hFlush stdout

declareEntryPoint 'initialize
