extern void log_qi_null_riid(const char *iface, void *This);
extern void log_qi_unknown_iid(const char *iface, void *This, REFIID riid);
extern void log_qi_null_ppvobject(const char *iface, void *This, REFIID riid);
extern void log_qi(const char *iface, void *This, REFIID riid);
extern void log_addref(const char *iface, void *This, LONG refs);
extern void log_release(const char *iface, void *This, LONG refs);
extern void log_plugin_initialize(void *This, void *pChannelMgr, ULONG refs);
extern void log_plugin_connected(void *This);
extern void log_plugin_disconnected(void *This, DWORD dwDisconnectCode);
extern void log_plugin_terminated(void *This, void *cm, ULONG refs);
extern void log_data_received(void *This, ULONG cbSize, BYTE *pBuffer);
extern void log_closed(void *This);
extern void log_new_connection_malloc_failed(void *This, void *pChannel);
extern void log_new_connection(void *This, void *pChannel, void *ccb);
extern void log_create_listener_malloc_failed(const char *channel_name, void *listener);
extern void log_create_listener(const char *channel_name, void *listener, void *lcb);
extern void log_create_listener_channel_manager_error(const char *channel_name, void *lcb, HRESULT hr);
extern void log_write_channel(void *channel, BYTE *bytes, ULONG len, HRESULT hr);
extern void log_close_channel(void *channel, HRESULT hr);
extern void log_vcgi_null_refiid(void);
extern void log_vcgi_unknown_iid(REFIID refiid);
extern void log_vcgi_null_pnumobjs(void);
extern void log_vcgi_too_small_numobjs(ULONG num);
extern void log_vcgi_get(void *inst);
extern void log_vcgi_count(void);
